name: web_socket_test
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  dio: ^4.0.6
  provider: ^6.0.5
  web_socket_channel: ^2.2.0
  sizer: ^2.0.15
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  # Add assets from the images directory to the application.
  # - assets/images/
  # - assets/translations/
