name: flutter_skeleton
description: Flutter Skeleton

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  provider: ^6.0.2
  easy_localization: ^3.0.0
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^8.1.0
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  # assets:
  # Add assets from the images directory to the application.
  # - assets/images/
  # - assets/translations/
